### ISSUE TITLE
rtl_433.conf vs rtl_433.conf.template

### ISSUE THREAD

**Issue by thekitehunter** [pbkhrv/rtl_433-hass-addons#102]
Since the last update, the addon seems to require an rtl_433.conf.template file instead of an rtl_433.conf file. This isn't clear in the installation instructions. Any rtl_433.conf file found is automatically deleted. Could this be made clearer and the reasoning behind it in the installation?

**Comment by deviantintegral** [comment]
This was changed to support multiple radios and automatic MQTT configuration, and was documented in the CHANGELOG (that shows up prior to upgrading) in the `0.1.3` release: https://github.com/pbkhrv/rtl_433-hass-addons/blob/main/rtl_433/CHANGELOG.md#013---2021-12-30
