### ISSUE TITLE
Invalid out of bounds values from rtl_433

### ISSUE THREAD

**Issue by joanwa** [pbkhrv/rtl_433-hass-addons#121]
### The problem

Every second day or so I observe values coming from rtl_433 that are out of bounds, mostly multiple readings at the same time. Reporting it here, but probably needs to be fixed in rtl_433 value templates or if someone has an idea on where best to fix this.

<img width="397" alt="Screenshot 2022-10-25 at 12 25 42" src="https://user-images.githubusercontent.com/7691102/197751509-368078ee-e6ab-431b-85ac-45b05db13156.png">
<img width="400" alt="Screenshot 2022-10-25 at 12 25 48" src="https://user-images.githubusercontent.com/7691102/197751513-5feec0be-2e91-4245-aaa7-3211290e6128.png">
<img width="393" alt="Screenshot 2022-10-25 at 12 31 51" src="https://user-images.githubusercontent.com/7691102/197751515-bdcc883a-dfd5-47e8-b6ec-c9d70b1cc513.png">

### What addon are you reporting the bug for?

rtl_443

### What is the addon version?

0.3.0

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

### Addon log messages

```txt
see attached pictures
```

**Comment by deviantintegral** [comment]
Yes, as long as you can confirm via `output kv` or looking in the MQTT messages, we'll know that this is an `rtl_433` issue.

I ran into something similar with my rain meter. I wonder if the decoder you're using is having trouble with corrupt messages too. See https://github.com/merbanan/rtl_433/issues/2105 for investigation hints.

**Comment by deviantintegral** [comment]
I'm closing this because the addon just takes rtl_433 values as is. If there's a patch upstream that improves this that we should consider patching in, feel free to open a new issue.
