### ISSUE TITLE
Trying to delete HA devices created by rtl_433 Auto Discovery

### ISSUE THREAD

**Issue by ifuchs** [pbkhrv/rtl_433-hass-addons#145]
### The problem

I am running rtl_433 auto discovery on HA without rtl_433 which is runnig on another machine and sending MQTT messages to HA. I need to delete a dozen or so devices which were created by auto discovery based on messages sent by an old version of rtl_433 running on the Pi. I have now upgraded rtl_433 and I would like to try again but I'd like to delete the devices that did not work. How to do that? I tried going to the MQTT broker device info for a device and when I tried to delete it, HA came back with "Device/service not found". I don't know to what that refers or how to complete the device deletions.

### What addon are you reporting the bug for?

rtl_433_mqtt_autodiscover

### What is the addon version?

0.6

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

**Comment by deviantintegral** [comment]
There's a delete device option in Home Assistant that should work in the overflow menu for "Device info":

<img width="686" alt="image" src="https://user-images.githubusercontent.com/255023/235451417-173e84f9-dcdd-4d48-b121-6be178bfd534.png">

**Comment by martinbaeuerle** [comment]
I've used rtl_433_autodiscovery to get access to the data send from my weatherstation, - just one. Litterly I've now close to 3000 entries in MQTT coming from rtl_433 service. A deletion on device by device is out of scope. 
1.) Are there any other option for delition of thousands of device entries
2.) How to avoid this broadcast of meanigless devices.

**Comment by deviantintegral** [comment]
To prevent adding devices you don’t want, you have a few options:

1. Add `protocol -<NUM>` to your rtl_433.config.template file to disable specific protocols. Or, add `protocol <NUM>` to only allow certain protocols. This will prevent rtl_433 from parsing those messages at all.
2. Only run the auto discovery addon when you are actually trying to add new devices. You may still get unwanted devices, but it should be on the order of a few, not thousands.

To delete all of the extra devices, if I remember right you can delete them in the MQTT broker using an MQTT tool like MQTT Explorer. The configuration is typically under `homeassistant/…`. I think once you delete them, they get removed from Home Assistant.

I think MQTT Explorer only lets you delete 50 topics at a time, which would still be annoying with 3000 to delete. In that case, you could use https://github.com/hivemq/mqtt-cli to write something to delete them all.
