### ISSUE TITLE
Support for Govee Water leak sensor

### ISSUE THREAD

**Issue by ifuchs** [pbkhrv/rtl_433-hass-addons#157]
### The problem

I have several Govee H5054 water leak sensors that I would like to bring into Home Assistant. rtl_433 Autodiscovery is seeing the device but only shows the battery status. My guess is that the key of interest is “event” which shows if there is a leak or if the button on the device is pressed. Home Assistant is adding the device but only with the battery_ok status. Could “event” be added as a valid key and would this solve the problem I am seeing?
If it helps, here is what MQTT explorer shows:
<img width="214" alt="Screenshot 2023-09-12 at 8 14 20 AM" src="https://github.com/pbkhrv/rtl_433-hass-addons/assets/5650376/5253ed8b-b411-4726-87fa-d06a093af358">

### What addon are you reporting the bug for?

rtl_433_mqtt_autodiscover

### What is the addon version?

0.6.0

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

### Addon log messages

```txt
INFO:root:Published Govee-Water/29010:  time
INFO:root:Skipped Govee-Water/29010:  event, code
```

**Comment by ifuchs** [comment]
I finally figured out how to replace the rtl_433_mqtt_hass.py file in the rtl_433 autodiscovery addin in HA. I restarted it and I caused a water leak transmission but although there is a Govee-water-29010 device, there are no entities (e.g., event) from the payload. MQTT explorer shows the mqtt received by HA.

**Comment by deviantintegral** [comment]
There’s some crossover, but given there’s more participation at https://github.com/merbanan/rtl_433/issues/2619 I’ll close this one for now. Thanks!
