### ISSUE TITLE
wind_max_km_h is not available for autodiscovery

### ISSUE THREAD

**Issue by Void-Seeker** [pbkhrv/rtl_433-hass-addons#17]
Weather station in my neighborhood sends "wind_max_km_h" field, but it is not available for autodiscovery.

**Comment by deviantintegral** [comment]
Should requests like this be in the rtl_433 project itself? We copy the script from https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_mqtt_hass.py into the container, so any fixes that make it into a stable rtl_433 release will eventually be pulled in here.

**Comment by thtro** [comment]
I've added this key to the main rtl_443 project, please update it for the next release, so it includes this, thanks!

**Comment by deviantintegral** [comment]
We've updated to the latest release in `next` so this should be available soon.
