### ISSUE TITLE
Device added by Auto Discovery doesn't persist across reboots. "This entity is no longer being provided by the mqtt integration"

### ISSUE THREAD

**Issue by Jsalas424** [pbkhrv/rtl_433-hass-addons#170]
### The problem

Using the "next" version of both auto discovery rtl_433 I was able to add the [Govee water sensors to HA](https://github.com/merbanan/rtl_433/pull/2605). After reboot, the entity shows up as no longer provided and all downstream automatons fail even though messages were received. 

<img width="565" alt="Screen Shot 2023-11-04 at 8 49 04 AM" src="https://github.com/pbkhrv/rtl_433-hass-addons/assets/51519895/0601bbfa-eff1-4776-b67a-e7dd604394b0">

If I run rtl_433 MQTT Auto Discovery (next) again and trigger the wet sensor, it reappears and persists up until I reboot again. 

<img width="1019" alt="Screen Shot 2023-11-04 at 12 25 43 PM" src="https://github.com/pbkhrv/rtl_433-hass-addons/assets/51519895/423d9ee3-f44b-4a81-b47c-61cc88f442d8">

<img width="1012" alt="Screen Shot 2023-11-04 at 8 48 11 AM" src="https://github.com/pbkhrv/rtl_433-hass-addons/assets/51519895/b097813e-0281-4366-a08b-276226e6828d">

### What addon are you reporting the bug for?

rtl_433_mqtt_autodiscover

### What is the addon version?

next

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

**Comment by deviantintegral** [comment]
Did you have the retain options set when running the auto discovery addon?

**Comment by Jsalas424** [comment]
> Did you have the retain options set when running the auto discovery addon?

No. Problem solved, thanks for the help.
