### ISSUE TITLE
Can't detect any signal with RTL-SDR.COM V4 dongle  because of old driver

### ISSUE THREAD

**Issue by szilard9554** [pbkhrv/rtl_433-hass-addons#194]
### The problem

With RTL-SDR.COM V4 dongle can't detect any signal because of old drivers - the issue is also mentioned on the official website.

I did a bit of research and I found out that if I change the source image from `ghcr.io/home-assistant/amd64-base:3.18` to `ghcr.io/home-assistant/amd64-base:latest` (version 3.20) works fine ... 

Thanks you

### What addon are you reporting the bug for?

rtl_443

### What is the addon version?

0.5.1

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

### Additional information

Old image 
e2653a95100b:/build/root/usr/local/bin# ./rtl_433 -f 433.889M  -Y autolevel
rtl_433 version 23.11 branch  at 202311281352 inputs file rtl_tcp RTL-SDR
Found Rafael Micro R828D tuner
[SDR] Using device 0: RTLSDRBlog, Blog V4, SN: 00000001, "Generic RTL2832U OEM"
Exact sample rate is: 250000.000414 Hz
[sdr_set_center_freq] Failed to set center freq.
Allocating 15 zero-copy buffers
[Auto Level] Estimated noise level is -17.0 dB, adjusting minimum detection level to -14.0 dB
[Auto Level] Estimated noise level is -18.8 dB, adjusting minimum detection level to -15.8 dB
[Auto Level] Estimated noise level is -20.4 dB, adjusting minimum detection level to -17.4 dB
[Auto Level] Estimated noise level is -21.8 dB, adjusting minimum detection level to -18.8 dB

New image 
bb95a510372a:/build/root/usr/local/bin# ./rtl_433 -f 433.889M  -Y autolevel
rtl_433 version 23.11 branch  at 202311281352 inputs file rtl_tcp RTL-SDR
Found Rafael Micro R828D tuner
RTL-SDR Blog V4 Detected
[SDR] Using device 0: RTLSDRBlog, Blog V4, SN: 00000001, "Generic RTL2832U OEM"
Exact sample rate is: 250000.000414 Hz
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2024-06-03 10:27:27
model     : Emax-W6      id        : d25
Channel   : 4            Battery_OK: 1             Temperature: 76.8 F       Humidity  : 55 %          Wind avg speed: 8.6 km/h  Wind Direction: 37        Total rainfall: 16.6 mm   UV Index  : 21            Lux       : 0
Integrity : CHECKSUM

**Comment by deviantintegral** [comment]
This should work if you install the `next` version of the addon. Can you confirm? I don't have a V4 dongle myself. If so, I will tag a new release of the stable one (which will have the same rtl_433 version but upgrade alpine underneath).
