### ISSUE TITLE
Repostitory structure for main is not compliant

### ISSUE THREAD

**Issue by hackstuces** [pbkhrv/rtl_433-hass-addons#2]
Hi,

Thanks for this great work. I would like to add this to my home assistant but I got this message "Repostitory structure for main is not compliant". Do you have any idea?

**Comment by pbkhrv** [comment]
Hi, thanks for reaching out. That error message looks like it might be coming from HACS (https://github.com/search?q=org%3Ahacs+%22Repository+structure+for%22&type=code)? These add-ons are meant for the Home Assistant itself, not HACS. Here's instructions about how to add this repo to your HA install: https://www.home-assistant.io/hassio/installing_third_party_addons/

Let me know whether that helps. Thanks.
