### ISSUE TITLE
SSL support not compiled in

### ISSUE THREAD

**Issue by jctrouble** [pbkhrv/rtl_433-hass-addons#204]
### The problem

The build of rtl_433 doesn't include support for mqtts (despite rtl_433 supporting it):

```
Starting rtl_433 with rtl_433.conf...
[rtl_433] rtl_433 version 23.11 branch  at 202311281352 inputs file rtl_tcp RTL-SDR
[rtl_433] MQTT: Publishing MQTT data to mqtt.my.external.broker.net port 8883 (TLS)
[rtl_433] MQTT: Publishing device info to MQTT topic "rtl_433/9b13b3f4-rtl433/devices[/type][/model][/subtype][/channel][/id]".
[rtl_433] MQTT: Publishing events info to MQTT topic "rtl_433/9b13b3f4-rtl433/events".
[rtl_433] MQTT: Publishing states info to MQTT topic "rtl_433/9b13b3f4-rtl433/states".
[rtl_433] MQTT: mqtts (TLS) parameters are: tls_cert=(null) tls_key=(null) tls_ca_cert=* tls_cipher_suites=(null) tls_server_name=(null) tls_psk_identity=(null) tls_psk_key=(null) 
[rtl_433] mqtt_client_init: mqtts (TLS) not available
```

That message comes from [here](https://github.com/merbanan/rtl_433/blob/e3c40fbc53ecf7b801f95eaff46e578b18928cc7/src/output_mqtt.c#L143-L154) due to `MG_ENABLE_SSL` not being defined, which is ultimately set whenever openssl is detected ([source](https://github.com/merbanan/rtl_433/blob/e3c40fbc53ecf7b801f95eaff46e578b18928cc7/CMakeLists.txt#L204-L210)).

I'm hoping it's as simple as adding `libopenssl-dev` (or whatever the package is) to the [Dockerfile](https://github.com/pbkhrv/rtl_433-hass-addons/blob/e334ffe7a7874544170acf74fd4b41a72953ef17/rtl_433/Dockerfile#L8-L13)

### What addon are you reporting the bug for?

rtl_443

### What is the addon version?

0.5.2

### What type of MQTT Broker are you using?

Other (details in the bug description)

### Addon log messages

```txt
Starting rtl_433 with rtl_433.conf...
[rtl_433] rtl_433 version 23.11 branch  at 202311281352 inputs file rtl_tcp RTL-SDR
[rtl_433] MQTT: Publishing MQTT data to mqtt.redacted.net port 8883 (TLS)
[rtl_433] MQTT: Publishing device info to MQTT topic "rtl_433/9b13b3f4-rtl433/devices[/type][/model][/subtype][/channel][/id]".
[rtl_433] MQTT: Publishing events info to MQTT topic "rtl_433/9b13b3f4-rtl433/events".
[rtl_433] MQTT: Publishing states info to MQTT topic "rtl_433/9b13b3f4-rtl433/states".
[rtl_433] MQTT: mqtts (TLS) parameters are: tls_cert=(null) tls_key=(null) tls_ca_cert=* tls_cipher_suites=(null) tls_server_name=(null) tls_psk_identity=(null) tls_psk_key=(null) 
[rtl_433] mqtt_client_init: mqtts (TLS) not available
```

**Comment by deviantintegral** [comment]
This will be in the `next` branch in a few minutes. Thanks!
