### ISSUE TITLE
Auto-discovery script uses invalid device_class "weather" for some devices

### ISSUE THREAD

**Issue by pbkhrv** [pbkhrv/rtl_433-hass-addons#5]
Upstream at rtl_433/examples/rtl_433_mqtt_hass.py uses "weather" as device_class in some places. There is an outstanding PR to fix that, but that's stuck behind some other PR etc etc. Temporarily pointing Dockerfile here to my own fork of rtl_433 with that script fixed. Will point back to upstream when merged there. Keeping this issue open until then.

**Comment by deviantintegral** [comment]
https://github.com/merbanan/rtl_433/pull/1584

**Comment by deviantintegral** [comment]
This has been merged upstream 🎉 .

**Comment by deviantintegral** [comment]
This has been pulled into the `next` branch.
