### ISSUE TITLE
autodiscover addon not seeing published sensor

### ISSUE THREAD

**Issue by DolfLund** [pbkhrv/rtl_433-hass-addons#57]
Add-on does not seem to properly recognize published sensor data.

Log says:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
mqtt found in this Home Assistance instance.
Starting rtl_433_mqtt_hass.py...
MQTT connected: Connection Accepted.

published topic looks like this:

![2022-01-22 01_22_40-MQTT Explorer](https://user-images.githubusercontent.com/57933629/150627647-70d905ec-0aed-4fdc-867b-8dcca0a32aa9.png)

**Comment by DolfLund** [comment]
user error

**Comment by peetipablo** [comment]
@DolfLund what was your user error, if you don't mind?  I'm having the same issue where I have published sensors, but the discovery addon is not publishing discovery information.
