### ISSUE TITLE
Protocols commented out still being detected

### ISSUE THREAD

**Issue by jayscovill** [pbkhrv/rtl_433-hass-addons#58]
I've commented out almost every protocol except of a few Acurite ones.  

My Acurite sensors are being detected by the SDR and add-on but so are a few other devices for protocols that I've commented out so I wonder if I'm missing something.

![image](https://user-images.githubusercontent.com/30603659/150649216-624487e2-8d92-49ae-962b-8d683c546d8c.png)

Could it just be that these guys happen to be using the same protocol?

**Comment by deviantintegral** [comment]
Do you have the "retain" option in use anywhere? You may need to manually delete the MQTT topics, and the devices in HA, and then restart to see if they are still added.

**Comment by deviantintegral** [comment]
Please re-open if you're still experiencing this. Thanks!
