### ISSUE TITLE
Enable long term statistics for rtl_433 sensors?

### ISSUE THREAD

**Issue by imagesafari** [pbkhrv/rtl_433-hass-addons#67]
Feature request: Enable long term statistics for rtl_433 sensors to enable graphing on a "Statistics Graph" card.

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by kdknigga** [comment]
This has been supported upstream since October 2021.

https://github.com/merbanan/rtl_433/pull/1835

**Comment by deviantintegral** [comment]
I'm an influx / grafana user, so this is new to me - but, this totally works! I have stats going back longer as I've been running the latest in development code. Upgrade to the latest release and stats should start to be saved.

<img width="513" alt="Screen Shot 2022-02-20 at 4 32 26 PM" src="https://user-images.githubusercontent.com/255023/154865150-f1a99892-5ae3-4bc2-b3e2-4221485943c1.png">

**Comment by imagesafari** [comment]
When I go in to create a Statistics Graph, none of the rtl_433 sensors show
up as supported. Is there some additional step that has to be done?

Most of my sensors are Acurite Tower sensors.

**Comment by imagesafari** [comment]
Nevermind, I updated to the latest addon and it looks like it is working
now. Thanks!
