### ISSUE TITLE
Using MQTT formats prevents rtl_433 from starting

### ISSUE THREAD

**Issue by nukefrenzy** [pbkhrv/rtl_433-hass-addons#79]
When I just use the following everything runs fine:

`output mqtt://192.168.1.13:1883,user=mqtt,pass=MYPASSWORD`

However, as soon as I start trying to change the topic structure, the addon just hangs and won't continue. Here's an example of what I'm trying to do:

`output mqtt://192.168.1.13:1883,user=mqtt,pass=MYPASSWORD,devices=rtl_433[/id]`

I have confirmed with the rtl_433 devs that my output string is correct and works with their code.  See here: https://github.com/merbanan/rtl_433/issues/1995

The below is all I see in the logs:

![image](https://user-images.githubusercontent.com/36387475/155585327-e9440916-35be-465e-995a-4835638fc575.png)

**Comment by deviantintegral** [comment]
I just gave this a try, and it looks to be working for me. Here's my whole configuration file:

```
device 0
output mqtt://${host}:${port},user=${username},pass=${password},retain=${retain},devices=asdf[/id]
report_meta time:iso:tz:local
convert si
output kv
verbose
```

<img width="319" alt="Screen Shot 2022-03-27 at 1 18 58 PM" src="https://user-images.githubusercontent.com/255023/160292887-aa9bceec-5215-4ce3-85c2-d52ad44fcc4f.png">

**Comment by nukefrenzy** [comment]
I pasted what you have above and it doesn't seem to work.  What do your logs show when using that config file?

**Comment by nukefrenzy** [comment]
Finally got some time to play around with this more.  I installed the MQTT Explorer app and I'm able to see the messages as they come in and everything is working fine with the "devices" info added to the output line.  What is weird is that the log just stops as shown in my original post whenever I add "devices".  When I remove it I get the full log output as shown below.  That's what tripped me up, I thought the add-on hung up.  I wonder why adding an extra parameter to the output would change the logging?

![image](https://user-images.githubusercontent.com/36387475/172464738-d3b534b4-5a13-42c8-a1f9-0d76b3d63fd8.png)

**Comment by deviantintegral** [comment]
We have a bug with output buffering that can cause logs to be delayed until there’s further input.

are you putting device before or after the output line? I think it needs to be first so it exists to reference in the output line.

**Comment by nukefrenzy** [comment]
Update: putting 'device 0' first does not fix the logging issue.  My logs still look like the screenshot in my first post.

**Comment by deviantintegral** [comment]
I've tagged a new release today which fixes the output buffering. Are you still having any trouble with this?

**Comment by nukefrenzy** [comment]
Everything looks normal in my logs again and everything is working well. Thanks for the update!
